// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { separator } from "./Separator.recipe";
import defaults from "./Separator.defaults";

export type SeparatorProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof separator> &
  StateOf<typeof separator>;

const Separator = defineComponent({
  recipe: separator,
  name: "Separator",
  defaults: defaults.Separator,
}) as unknown as (
  props: SeparatorProps,
) => JSX.Element;

export type SeparatorOrientation = NonNullable<
  PropsOf<typeof separator>["orientation"]
>;
export type SeparatorVariant = NonNullable<
  PropsOf<typeof separator>["variant"]
>;


export default Separator;
export { Separator };
