// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { badge } from "./Badge.recipe";
import defaults from "./Badge.defaults";
import { BadgeRootLayout, BadgeAnchorLayout, BadgeLabelLayout } from "./Badge.layout";

export type BadgeRootProps = JSX.HTMLAttributes<HTMLSpanElement> &
  IComponentBaseProps &
  PropsOf<typeof badge> &
  StateOf<typeof badge>;

const BadgeRoot = defineComponent({
  recipe: badge,
  name: "BadgeRoot",
  defaults: defaults.Badge,
  layout: BadgeRootLayout,
}) as unknown as (
  props: BadgeRootProps,
) => JSX.Element;

export type BadgeAnchorProps = JSX.HTMLAttributes<HTMLSpanElement> & IComponentBaseProps;

const BadgeAnchor = defineComponent({
  recipe: badge,
  name: "BadgeAnchor",
  slot: "anchor",
  layout: BadgeAnchorLayout,
}) as unknown as (
  props: BadgeAnchorProps,
) => JSX.Element;

export type BadgeLabelProps = JSX.HTMLAttributes<HTMLSpanElement> & IComponentBaseProps;

const BadgeLabel = defineComponent({
  recipe: badge,
  name: "BadgeLabel",
  slot: "label",
  layout: BadgeLabelLayout,
}) as unknown as (
  props: BadgeLabelProps,
) => JSX.Element;

export type BadgeSize = NonNullable<
  PropsOf<typeof badge>["size"]
>;
export type BadgeColor = NonNullable<
  PropsOf<typeof badge>["color"]
>;
export type BadgeVariant = NonNullable<
  PropsOf<typeof badge>["variant"]
>;
export type BadgePlacement = NonNullable<
  PropsOf<typeof badge>["placement"]
>;
export type BadgeProps = BadgeRootProps;

const Badge = compound(BadgeRoot, {
  Anchor: BadgeAnchor,
  Label: BadgeLabel,
});

export default Badge;
export { Badge, BadgeRoot, BadgeAnchor, BadgeLabel };
