// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { text } from "./Text.recipe";
import { TextLayout } from "./Text.layout";

export type TextProps = JSX.HTMLAttributes<HTMLSpanElement> &
  IComponentBaseProps &
  PropsOf<typeof text> &
  StateOf<typeof text>;

const Text = defineComponent({
  recipe: text,
  name: "Text",
  layout: TextLayout,
}) as unknown as (
  props: TextProps,
) => JSX.Element;

export type TextSize = NonNullable<
  PropsOf<typeof text>["size"]
>;
export type TextVariant = NonNullable<
  PropsOf<typeof text>["variant"]
>;


export default Text;
export { Text };
