// Named rather than left as the default export. The package root
// re-exports this module's `default` and its `toast` function in one
// block, and the bundler collapsed both onto `toast`: `Toast` in the
// built entry became the toast *function*, so `Toast.Provider` and every
// other compound member was undefined for consumers.
export {
  DEFAULT_GAP,
  DEFAULT_MAX_VISIBLE_TOAST,
  DEFAULT_SCALE_FACTOR,
  DEFAULT_TOAST_TIMEOUT,
  DEFAULT_TOAST_WIDTH,
  default,
  default as Toast,
  type HeroUIToastOptions,
  ToastActionButton,
  type ToastActionButtonProps,
  type ToastActionProps,
  ToastCloseButton,
  type ToastCloseButtonProps,
  ToastContent,
  type ToastContentProps,
  type ToastContentValue,
  ToastDescription,
  type ToastDescriptionProps,
  type ToastFunction,
  ToastIndicator,
  type ToastIndicatorProps,
  type ToastPlacement,
  type ToastPromiseOptions,
  ToastProvider,
  type ToastProviderProps,
  ToastQueue,
  type ToastQueueAddOptions,
  type ToastQueueItem,
  type ToastQueueOptions,
  type ToastRenderFn,
  ToastRoot,
  type ToastRootProps,
  ToastTitle,
  type ToastTitleProps,
  type ToastVariant,
  toast,
  toastQueue,
} from "./Toast.generated";
