// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { fieldset } from "./Fieldset.recipe";
import { FieldsetRootLayout, FieldsetLegendLayout, FieldsetGroupLayout, FieldsetActionsLayout } from "./Fieldset.layout";

export type FieldsetRootProps = JSX.HTMLAttributes<HTMLFieldSetElement> &
  IComponentBaseProps &
  PropsOf<typeof fieldset> &
  StateOf<typeof fieldset>;

const FieldsetRoot = defineComponent({
  recipe: fieldset,
  name: "FieldsetRoot",
  layout: FieldsetRootLayout,
}) as unknown as (
  props: FieldsetRootProps,
) => JSX.Element;

export type FieldsetLegendProps = JSX.HTMLAttributes<HTMLFieldSetElement> & IComponentBaseProps;

const FieldsetLegend = defineComponent({
  recipe: fieldset,
  name: "FieldsetLegend",
  slot: "legend",
  layout: FieldsetLegendLayout,
}) as unknown as (
  props: FieldsetLegendProps,
) => JSX.Element;

export type FieldsetGroupProps = JSX.HTMLAttributes<HTMLFieldSetElement> & IComponentBaseProps;

const FieldsetGroup = defineComponent({
  recipe: fieldset,
  name: "FieldsetGroup",
  slot: "group",
  layout: FieldsetGroupLayout,
}) as unknown as (
  props: FieldsetGroupProps,
) => JSX.Element;

export type FieldsetActionsProps = JSX.HTMLAttributes<HTMLFieldSetElement> & IComponentBaseProps;

const FieldsetActions = defineComponent({
  recipe: fieldset,
  name: "FieldsetActions",
  slot: "actions",
  layout: FieldsetActionsLayout,
}) as unknown as (
  props: FieldsetActionsProps,
) => JSX.Element;

export type FieldsetProps = FieldsetRootProps;

const Fieldset = compound(FieldsetRoot, {
  Legend: FieldsetLegend,
  Group: FieldsetGroup,
  Actions: FieldsetActions,
});

export default Fieldset;
export { Fieldset, FieldsetRoot, FieldsetLegend, FieldsetGroup, FieldsetActions };
