// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { spinner } from "./Spinner.recipe";
import defaults from "./Spinner.defaults";
import { SpinnerLayout } from "./Spinner.layout";

export type SpinnerProps = JSX.HTMLAttributes<HTMLSpanElement> &
  IComponentBaseProps &
  PropsOf<typeof spinner> &
  StateOf<typeof spinner>;

const Spinner = defineComponent({
  recipe: spinner,
  name: "Spinner",
  defaults: defaults.Spinner,
  layout: SpinnerLayout,
}) as unknown as (
  props: SpinnerProps,
) => JSX.Element;

export type SpinnerSize = NonNullable<
  PropsOf<typeof spinner>["size"]
>;
export type SpinnerColor = NonNullable<
  PropsOf<typeof spinner>["color"]
>;
export type SpinnerVariant = NonNullable<
  PropsOf<typeof spinner>["variant"]
>;


export default Spinner;
export { Spinner };
