// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { skeleton } from "./Skeleton.recipe";
import defaults from "./Skeleton.defaults";

export type SkeletonProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof skeleton> &
  StateOf<typeof skeleton>;

const Skeleton = defineComponent({
  recipe: skeleton,
  name: "Skeleton",
  defaults: defaults.Skeleton,
}) as unknown as (
  props: SkeletonProps,
) => JSX.Element;

export type SkeletonAnimation = NonNullable<
  PropsOf<typeof skeleton>["animation"]
>;


export default Skeleton;
export { Skeleton };
