export const CLASSES = {
  landing: {
    base: "immersive-landing",
    viewport: "immersive-landing__viewport",
    pageLayer: "immersive-landing__page-layer",
    overlay: "immersive-landing__overlay",
    versionWrap: "immersive-landing__version-wrap",
    versionLabel: "immersive-landing__version-label",
  },
  page: {
    base: "immersive-landing-page",
    active: "immersive-landing-page--active",
    inactive: "immersive-landing-page--inactive",
    content: "immersive-landing-page__content",
  },
  arrows: {
    button: "immersive-landing-arrows__button",
    prev: "immersive-landing-arrows__button--prev",
    next: "immersive-landing-arrows__button--next",
    icon: "immersive-landing-arrows__icon",
  },
  navigation: {
    base: "immersive-landing-navigation",
    shell: "immersive-landing-navigation__shell",
    row: "immersive-landing-navigation__row",
    mobileArrow: "immersive-landing-navigation__mobile-arrow",
    mobileArrowDisabled: "immersive-landing-navigation__mobile-arrow--disabled",
    dots: "immersive-landing-navigation__dots",
    dot: "immersive-landing-navigation__dot",
    dotActive: "immersive-landing-navigation__dot--active",
    counter: "immersive-landing-navigation__counter",
    icon: "immersive-landing-navigation__icon",
  },
  pwaPrompt: {
    dialog: "immersive-landing-pwa",
    card: "immersive-landing-pwa__card",
    closeButton: "immersive-landing-pwa__close",
    body: "immersive-landing-pwa__body",
    media: "immersive-landing-pwa__media",
    appIconWrap: "immersive-landing-pwa__app-icon-wrap",
    appIcon: "immersive-landing-pwa__app-icon",
    textWrap: "immersive-landing-pwa__text-wrap",
    title: "immersive-landing-pwa__title",
    description: "immersive-landing-pwa__description",
    footer: "immersive-landing-pwa__footer",
    action: "immersive-landing-pwa__action",
  },
  firefoxBanner: {
    dialog: "immersive-landing-firefox",
    card: "immersive-landing-firefox__card",
    closeButton: "immersive-landing-firefox__close",
    body: "immersive-landing-firefox__body",
    media: "immersive-landing-firefox__media",
    iconWrap: "immersive-landing-firefox__icon-wrap",
    browserIcon: "immersive-landing-firefox__browser-icon",
    textWrap: "immersive-landing-firefox__text-wrap",
    title: "immersive-landing-firefox__title",
    description: "immersive-landing-firefox__description",
    footer: "immersive-landing-firefox__footer",
    action: "immersive-landing-firefox__action",
  },
  cookie: {
    banner: "immersive-landing-cookie",
    bannerClosing: "immersive-landing-cookie--closing",
    container: "immersive-landing-cookie__container",
    row: "immersive-landing-cookie__row",
    message: "immersive-landing-cookie__message",
    actions: "immersive-landing-cookie__actions",
    actionButton: "immersive-landing-cookie__action-button",
    manageButton: "immersive-landing-cookie__manage-button",
    modalBackdrop: "immersive-landing-cookie__modal-backdrop",
    modalCard: "immersive-landing-cookie__modal-card",
    modalHeader: "immersive-landing-cookie__modal-header",
    modalTitle: "immersive-landing-cookie__modal-title",
    preferences: "immersive-landing-cookie__preferences",
    preferenceRow: "immersive-landing-cookie__preference-row",
    preferenceRowLocked: "immersive-landing-cookie__preference-row--locked",
    preferenceLabel: "immersive-landing-cookie__preference-label",
    toggle: "immersive-landing-cookie__toggle",
    modalFooter: "immersive-landing-cookie__modal-footer",
    saveButton: "immersive-landing-cookie__save-button",
  },
} as const;

