// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { card } from "./Card.recipe";
import defaults from "./Card.defaults";
import { CardRootLayout, CardHeaderLayout, CardBodyLayout, CardFooterLayout } from "./Card.layout";
import { createCard } from "./card";

export type CardRootProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof card> &
  StateOf<typeof card>;

const CardRoot = defineComponent({
  recipe: card,
  name: "CardRoot",
  defaults: defaults.Card,
  setup: createCard,
  layout: CardRootLayout,
}) as unknown as (
  props: CardRootProps,
) => JSX.Element;

export type CardHeaderProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const CardHeader = defineComponent({
  recipe: card,
  name: "CardHeader",
  slot: "header",
  layout: CardHeaderLayout,
}) as unknown as (
  props: CardHeaderProps,
) => JSX.Element;

export type CardBodyProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const CardBody = defineComponent({
  recipe: card,
  name: "CardBody",
  slot: "body",
  layout: CardBodyLayout,
}) as unknown as (
  props: CardBodyProps,
) => JSX.Element;

export type CardFooterProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const CardFooter = defineComponent({
  recipe: card,
  name: "CardFooter",
  slot: "footer",
  layout: CardFooterLayout,
}) as unknown as (
  props: CardFooterProps,
) => JSX.Element;

export type CardVariant = NonNullable<
  PropsOf<typeof card>["variant"]
>;
export type CardIsHoverable = NonNullable<
  PropsOf<typeof card>["isHoverable"]
>;
export type CardIsPressable = NonNullable<
  PropsOf<typeof card>["isPressable"]
>;
export type CardProps = CardRootProps;

const Card = compound(CardRoot, {
  Header: CardHeader,
  Body: CardBody,
  Footer: CardFooter,
});

export default Card;
export { Card, CardRoot, CardHeader, CardBody, CardFooter };
