// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { icon } from "./Icon.recipe";
import { IconLayout } from "./Icon.layout";
import { createIcon } from "./icon";
import type { Props as BehaviourProps } from "./icon";

export type IconProps = JSX.HTMLAttributes<HTMLSpanElement> &
  IComponentBaseProps &
  PropsOf<typeof icon> &
  StateOf<typeof icon> &
  BehaviourProps;

const Icon = defineComponent({
  recipe: icon,
  name: "Icon",
  behaviour: ["name", "width", "height"],
  setup: createIcon,
  layout: IconLayout,
}) as unknown as (
  props: IconProps,
) => JSX.Element;


export default Icon;
export { Icon };
