// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { alert } from "./Alert.recipe";
import defaults from "./Alert.defaults";
import { AlertRootLayout, AlertIndicatorLayout, AlertContentLayout, AlertTitleLayout, AlertDescriptionLayout } from "./Alert.layout";
import { AlertContext } from "./Alert.context";

export type AlertRootProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof alert> &
  StateOf<typeof alert>;

const AlertRoot = defineComponent({
  recipe: alert,
  name: "AlertRoot",
  defaults: defaults.Alert,
  provide: AlertContext,
  layout: AlertRootLayout,
}) as unknown as (
  props: AlertRootProps,
) => JSX.Element;

export type AlertIndicatorProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const AlertIndicator = defineComponent({
  recipe: alert,
  name: "AlertIndicator",
  slot: "indicator",
  layout: AlertIndicatorLayout,
}) as unknown as (
  props: AlertIndicatorProps,
) => JSX.Element;

export type AlertContentProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const AlertContent = defineComponent({
  recipe: alert,
  name: "AlertContent",
  slot: "content",
  layout: AlertContentLayout,
}) as unknown as (
  props: AlertContentProps,
) => JSX.Element;

export type AlertTitleProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const AlertTitle = defineComponent({
  recipe: alert,
  name: "AlertTitle",
  slot: "title",
  layout: AlertTitleLayout,
}) as unknown as (
  props: AlertTitleProps,
) => JSX.Element;

export type AlertDescriptionProps = JSX.HTMLAttributes<HTMLDivElement> & IComponentBaseProps;

const AlertDescription = defineComponent({
  recipe: alert,
  name: "AlertDescription",
  slot: "description",
  layout: AlertDescriptionLayout,
}) as unknown as (
  props: AlertDescriptionProps,
) => JSX.Element;

export type AlertStatus = NonNullable<
  PropsOf<typeof alert>["status"]
>;
export type AlertProps = AlertRootProps;

const Alert = compound(AlertRoot, {
  Indicator: AlertIndicator,
  Content: AlertContent,
  Title: AlertTitle,
  Description: AlertDescription,
});

export default Alert;
export { Alert, AlertRoot, AlertIndicator, AlertContent, AlertTitle, AlertDescription };
