export const CLASSES = {
  bubble: {
    base: "live-chat-bubble",
    position: {
      right: "live-chat-bubble--right",
      left: "live-chat-bubble--left",
    },
    icon: "live-chat-bubble__icon",
    badge: "live-chat-bubble__badge",
    ping: "live-chat-bubble__ping",
  },
  panel: {
    base: "live-chat-panel",
    header: "live-chat-panel__header",
    headerTitleWrap: "live-chat-panel__header-title-wrap",
    headerIcon: "live-chat-panel__header-icon",
    headerTitle: "live-chat-panel__header-title",
    closeButton: "live-chat-panel__close-button",
    closeIcon: "live-chat-panel__close-icon",
    messages: "live-chat-panel__messages",
    row: "live-chat-panel__row",
    rowUser: "live-chat-panel__row--user",
    rowAgent: "live-chat-panel__row--agent",
    avatar: "live-chat-panel__avatar",
    avatarUser: "live-chat-panel__avatar--user",
    avatarAgent: "live-chat-panel__avatar--agent",
    messageColumn: "live-chat-panel__message-column",
    messageColumnUser: "live-chat-panel__message-column--user",
    messageColumnAgent: "live-chat-panel__message-column--agent",
    messageBubble: "live-chat-panel__message-bubble",
    messageBubbleUser: "live-chat-panel__message-bubble--user",
    messageBubbleAgent: "live-chat-panel__message-bubble--agent",
    messageText: "live-chat-panel__message-text",
    timestamp: "live-chat-panel__timestamp",
    empty: "live-chat-panel__empty",
    inputArea: "live-chat-panel__input-area",
    input: "live-chat-panel__input",
    sendButton: "live-chat-panel__send-button",
    spinner: "live-chat-panel__spinner",
  },
} as const;
