export {
  default,
  DialogRoot,
  DialogTrigger,
  DialogBackdrop,
  DialogContent,
  DialogHeader,
  DialogHeading,
  DialogIcon,
  DialogBody,
  DialogFooter,
  DialogCloseTrigger,
  type DialogProps,
  type DialogPanelProps,
  type DialogPlacement,
  type DialogSize,
  type DialogBackdropVariant,
  type DialogScrollBehavior,
  type DialogRootProps,
  type DialogTriggerProps,
  type DialogBackdropProps,
  type DialogContentProps,
  type DialogHeaderProps,
  type DialogHeadingProps,
  type DialogIconProps,
  type DialogBodyProps,
  type DialogFooterProps,
  type DialogCloseTriggerProps,
} from "./Dialog.generated";
