export {
  DialogBackdrop,
  type DialogBackdropProps,
  type DialogBackdropVariant,
  DialogBody,
  type DialogBodyProps,
  DialogCloseTrigger,
  type DialogCloseTriggerProps,
  DialogContent,
  type DialogContentProps,
  DialogFooter,
  type DialogFooterProps,
  DialogHeader,
  type DialogHeaderProps,
  DialogHeading,
  type DialogHeadingProps,
  DialogIcon,
  type DialogIconProps,
  type DialogPanelProps,
  type DialogPlacement,
  type DialogProps,
  DialogRoot,
  type DialogRootProps,
  type DialogScrollBehavior,
  type DialogSize,
  DialogTrigger,
  type DialogTriggerProps,
  default,
} from "./Dialog.generated";
