// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { closeButton } from "./CloseButton.recipe";
import defaults from "./CloseButton.defaults";
import { CloseButtonLayout } from "./CloseButton.layout";
import { createCloseButton } from "./close-button";
import type { Props as BehaviourProps } from "./close-button";

export type CloseButtonProps = JSX.HTMLAttributes<HTMLButtonElement> &
  IComponentBaseProps &
  PropsOf<typeof closeButton> &
  StateOf<typeof closeButton> &
  BehaviourProps;

const CloseButton = defineComponent({
  recipe: closeButton,
  name: "CloseButton",
  defaults: defaults.CloseButton,
  behaviour: ["isDisabled", "isPending", "startIcon", "endIcon", "type", "aria-label"],
  setup: createCloseButton,
  layout: CloseButtonLayout,
}) as unknown as (
  props: CloseButtonProps,
) => JSX.Element;

export type CloseButtonVariant = NonNullable<
  PropsOf<typeof closeButton>["variant"]
>;


export default CloseButton;
export { CloseButton };
