// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { glowCard } from "./GlowCard.recipe";
import { GlowCardLayout } from "./GlowCard.layout";
import { createGlowCard } from "./glow-card";

export type GlowCardProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof glowCard> &
  StateOf<typeof glowCard>;

const GlowCard = defineComponent({
  recipe: glowCard,
  name: "GlowCard",
  setup: createGlowCard,
  layout: GlowCardLayout,
}) as unknown as (
  props: GlowCardProps,
) => JSX.Element;

export type GlowCardIsolate = NonNullable<
  PropsOf<typeof glowCard>["isolate"]
>;


export default GlowCard;
export { GlowCard };
