// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { kbd } from "./Kbd.recipe";
import defaults from "./Kbd.defaults";
import { KbdRootLayout, KbdAbbrLayout, KbdContentLayout } from "./Kbd.layout";

export type KbdRootProps = JSX.HTMLAttributes<HTMLElement> &
  IComponentBaseProps &
  PropsOf<typeof kbd> &
  StateOf<typeof kbd>;

const KbdRoot = defineComponent({
  recipe: kbd,
  name: "KbdRoot",
  defaults: defaults.Kbd,
  layout: KbdRootLayout,
}) as unknown as (
  props: KbdRootProps,
) => JSX.Element;

export type KbdAbbrProps = JSX.HTMLAttributes<HTMLElement> & IComponentBaseProps;

const KbdAbbr = defineComponent({
  recipe: kbd,
  name: "KbdAbbr",
  slot: "abbr",
  layout: KbdAbbrLayout,
}) as unknown as (
  props: KbdAbbrProps,
) => JSX.Element;

export type KbdContentProps = JSX.HTMLAttributes<HTMLElement> & IComponentBaseProps;

const KbdContent = defineComponent({
  recipe: kbd,
  name: "KbdContent",
  slot: "content",
  layout: KbdContentLayout,
}) as unknown as (
  props: KbdContentProps,
) => JSX.Element;

export type KbdVariant = NonNullable<
  PropsOf<typeof kbd>["variant"]
>;
export type KbdProps = KbdRootProps;

const Kbd = compound(KbdRoot, {
  Abbr: KbdAbbr,
  Content: KbdContent,
});

export default Kbd;
export { Kbd, KbdRoot, KbdAbbr, KbdContent };
