// Generated by scripts/generate-index.ts. Do not edit.
//
// The wiring is mechanical — which slots exist, whether there is a layout,
// whether there is behaviour to run — so it is generated rather than typed
// out. Edit the recipe, the layout or the behaviour module instead.

import type { JSX } from "solid-js";
import { compound, defineComponent } from "solid-layouts";
import type { PropsOf, StateOf } from "solid-layouts";

import type { IComponentBaseProps } from "../types";

import { surface } from "./Surface.recipe";
import defaults from "./Surface.defaults";

export type SurfaceProps = JSX.HTMLAttributes<HTMLDivElement> &
  IComponentBaseProps &
  PropsOf<typeof surface> &
  StateOf<typeof surface>;

const Surface = defineComponent({
  recipe: surface,
  name: "Surface",
  defaults: defaults.Surface,
}) as unknown as (
  props: SurfaceProps,
) => JSX.Element;

export type SurfaceVariant = NonNullable<
  PropsOf<typeof surface>["variant"]
>;


export default Surface;
export { Surface };
