/*
 * Build config for the QA harness.
 *
 * Separate from `rslib.config.ts`, which builds the library: this is an
 * application, and it consumes the library from source so a check runs against
 * the working tree rather than the last publish.
 */
import { defineConfig } from "@rsbuild/core";
import { pluginSolid } from "@rsbuild/plugin-solid";
import { pluginBabel } from "@rsbuild/plugin-babel";
import { pluginSolidLayoutsApplication } from "rsbuild-plugin-solid-layouts";
import { resolve } from "node:path";
import { COMPONENTS } from "./components";

export default defineConfig({
  root: __dirname,
  plugins: [
    // The *application* variant, as AgencyZero uses. The library variant
    // compiles `*.layout.tsx` sources; this one wires `solid-layouts` for a
    // consumer, which is what the harness is.
    pluginSolidLayoutsApplication(),
    pluginBabel({ include: /\.(?:jsx|tsx)$/ }),
    // `moduleName`/`generate` for the same reason `rslib.config.ts` sets them:
    // `@rsbuild/plugin-solid` resolves a nested Solid 1 preset whose transform
    // emits `solid-js/web`, a subpath Solid 2 dropped. Without this the harness
    // builds and then fails to resolve at runtime.
    pluginSolid({
      solidPresetOptions: { moduleName: "@solidjs/web", generate: "dom" },
    }),
  ],
  /*
   * One entry per component, generated by `qa/generate-entries.ts`.
   *
   * A single bundle put all 71 components in one module graph, so one that
   * throws on import emptied the page for all of them. A bundle each confines
   * that to the component responsible.
   */
  source: {
    entry: Object.fromEntries(
      COMPONENTS.map((spec) => [
        spec.id,
        resolve(__dirname, "entries", `${spec.id}.tsx`),
      ]),
    ),
  },
  /*
   * Resolve to `dist`, as a real consumer does, and rebuild the library before
   * running the harness (`qa:build` does both). Aliasing to `src` instead pulls
   * `solid-layouts` in uncompiled, which fails to link.
   *
   * This still tests the working tree rather than the last publish, because the
   * `dist` being read is the one just built from it.
   */
  resolve: {
    alias: {
      // The package *directory*, so `@pathscale/ui/components/<name>` resolves to
      // that component's own module. Aliasing the root file instead makes every
      // subpath import fail to link.
      "@pathscale/ui": resolve(__dirname, "../dist"),
    },
  },
  /*
   * One page per entry, each named for its component, so `blitz-preview` can be
   * pointed at exactly one component's dist: `<id>.html` beside `<id>.js`.
   */
  html: {
    template: resolve(__dirname, "index.html"),
    outputStructure: "flat",
  },
  server: { port: 5178 },
  output: {
    distPath: { root: resolve(__dirname, "dist") },
    /*
     * One JS and one CSS file, uncompressed names, no hashing: `blitz-preview`
     * reads the first `src=` and `href=` out of index.html and inlines them, so
     * a split bundle would leave chunks it never loads and the page would mount
     * nothing.
     */
    filenameHash: false,
  },
  performance: {
    chunkSplit: { strategy: "all-in-one" },
  },
});
